services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_NAME}:latest
    container_name: puzzle_academy_api
    ports:
      - "${APP_PORT:-3001}:3001"
    environment:
      NODE_ENV: production
      DATABASE_URL: "${DATABASE_URL}"
      RIOT_API_KEY: "${RIOT_API_KEY}"
      RIOT_REGION: "${RIOT_REGION}"
      RIOT_URL_ACCOUNT: "${RIOT_URL_ACCOUNT}"
      RIOT_URL_SUMMONER: "${RIOT_URL_SUMMONER}"
      PORT: "${APP_PORT}"
      SEASON_START_DATE: "${SEASON_START_DATE}"
      RABBITMQ_URL: "${RABBITMQ_URL}"
    networks:
      - m2a_network
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: puzzle_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-puzzle}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS:-puzzle}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - m2a_network
    restart: always

networks:
  m2a_network:
    external: true

volumes:
  rabbitmq_data:
