services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE_NAME}:latest
    container_name: puzzle_academy_api
    ports:
      - "${APP_PORT:-3001}:3001"
    environment:
      NODE_ENV: production
      DATABASE_URL: "${DATABASE_URL}"
      RIOT_API_KEY: "${RIOT_API_KEY}"
      RIOT_REGION: "${RIOT_REGION}"
      RIOT_URL_ACCOUNT: "${RIOT_URL_ACCOUNT}"
      RIOT_URL_SUMMONER: "${RIOT_URL_SUMMONER}"
      PORT: "${APP_PORT}"
    networks:
      - m2a_network
    restart: always

networks:
  m2a_network:
    external: true
