name: Deploy Puzzle Academy API

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  e2e-tests:
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  build-and-deploy:
    needs: [unit-tests, e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_IMAGE_NAME }}:latest

      - name: Prepare Docker Compose File
        id: read_compose
        run: |
          COMPOSE_CONTENT=$(base64 < docker-compose.prod.yml | tr -d '\n')
          echo "COMPOSE_FILE_CONTENT=$COMPOSE_CONTENT" >> $GITHUB_ENV

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          RIOT_REGION: BR1
          RIOT_URL_ACCOUNT: americas.api.riotgames.com
          RIOT_URL_SUMMONER: br1.api.riotgames.com
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
          COMPOSE_FILE_CONTENT: ${{ env.COMPOSE_FILE_CONTENT }}
          APP_PORT: ${{ vars.APP_PORT }}
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DATABASE_URL,RIOT_API_KEY,RIOT_REGION,RIOT_URL_ACCOUNT,RIOT_URL_SUMMONER,DOCKER_IMAGE_NAME,COMPOSE_FILE_CONTENT,APP_PORT
          script: |
            cd /home/${{ secrets.VPS_USER }}/puzzle-api
            
            # Decode the compose file content
            echo "$COMPOSE_FILE_CONTENT" | base64 -d > docker-compose.yml
            
            export DATABASE_URL="$DATABASE_URL"
            export RIOT_API_KEY="$RIOT_API_KEY"
            export RIOT_REGION="$RIOT_REGION"
            export RIOT_URL_ACCOUNT="$RIOT_URL_ACCOUNT"
            export RIOT_URL_SUMMONER="$RIOT_URL_SUMMONER"
            export DOCKER_IMAGE_NAME="$DOCKER_IMAGE_NAME"
            export APP_PORT="$APP_PORT"

            docker pull "${DOCKER_IMAGE_NAME}:latest"

            echo "--- STARTING PRISMA MIGRATION ---"
            docker run --rm \
              --network m2a_network \
              -e DATABASE_URL="$DATABASE_URL" \
              $DOCKER_IMAGE_NAME:latest \
              npx prisma migrate deploy
            
            docker compose up -d
